### ISSUE TITLE
Crash Report -283246263

### ISSUE THREAD

**Issue by wotktestact** [wowsims/wotlk#1049]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjkuVgMmCyYPRgDGBKYCxgamBknMDIuIGR6QAj4wVGRichDkYJRgUmDcYAxgLGFYyMOxgZhRikFrE2MbIF5CRWphZxsAuwSx1j5BIQuL+HSeL8PSYltm2Hmc7tYOLiFPh6h0mJGcTkFTgDlDx+D8rlELi8m0ni1lpmoK7TQImTt4G6Du8A6+ITuLWLSeIIUITl3FkmBiD/BFDF9bXMSiyrTgL5nAKXdwGNWXOSCaj5FFDq2Wqg5v07mEAivALrgQa/ACpm/gU0i0Vg1h4Q2bUTRL7ZCyL7loDt38YkceY2iLVmC4TFItC0m0mJAxgajAEsESxaJ5gYRgFVQBUnB6MAkwQoaU1iVOES4eIA8xkVQCmLUYPFAZj4gGmKi4NJACLC1MWobmBqbGBsYGhqpGtsYGJgamBgbAgkjQyNjYHihoZAHkjA8BEjD8fhI0wCe44wSZx+yvSCkeUDI8csRoZbjAxKS5g5IQ7wcxCEMEQcJGfNBIGT9pYQkQv2imlgcM3e6AtTwZzaKp6AxJLkjPLUomwFI1OFYAmOQZsSWhyoYUrDySOUmGNgoVXgSKxicKA3zD7t4AiJhp/2HowAHd+FiA==

RNG Seed: 3774229922

Trying to cast {SpellID: 60043} but is still on cooldown for 7.915403058s, curTime = 50.172598587s
Stack Trace:
goroutine 25 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xbc160, 0x66d8c90})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncCooldown.func1(0x6f0ae00, 0xa7fa000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:242 +0x20
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x6f0ae00, 0xa7fa000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:226 +0x20
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x6f0ae00, 0xa7fa000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:200 +0x13
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
This seems to be fixed now.
