### ISSUE TITLE
Crash Report 898183510

### ISSUE THREAD

**Issue by Khaniv5** [wowsims/wotlk#1217]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztUT0sg1EU/c79vrTPJ5JHDA+D6oRE8rTpwNKPyWCQWIwMxGAQG1MjBmniZ6KtSCSqhHQxmcXSGBQtUUojadKFiKmJxXutDjYDm5OXm3vPPfe8l3ftdkacJE1jFiHgAEgDJaAMShOFCINtHAIeSDhKsvwloQKoDPQbTUbrobUI18jMxPzkHAO3W1dgM363T+LikWyLJ6/IrucfeyS2n8gLQzXXEiRySVM1cwmy3TyeqDTq+buair2bunDz0/2afJdE8Ui7hK9JnN9XaIsfXmr7jVsdV+M6vqqc8QdlUtgxba05OCYvY5ZsGDHHzO51Mv7xDQsuBkEeLJLL1rs0wujy+WVA+mSgp0dl6vh7A1L6FeGTUupcMX5F9j5DsM0M8a0MiZcieSIZ6oxkSUazVIL1BncMdY1TFdwET4AcDG+e6ioXh6acxuoTmp2WWFQjFeyrMulgR23KlyTPqGB/vrkl5zdcQqmzX/H5Cap/NZx3Bqp1OTiEcXwC08hpzg==

RNG Seed: 880925703

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe58e0, 0x1218020})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x7a650a0, 0x7a74a00)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:93 +0x2
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).RotationActionCallback_RD(0x7b1b000, 0x7a650a0, 0x7a74a00, 0x7af7dd0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:193 +0x4
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:206
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).DoRotation(0x7b1b000, 0x7a650a0)
	/home/runner/work/wotlk/wotlk/sim

**Comment by JooperGH** [comment]
The tank sim isn't fully functional still. Do not use it.
