### ISSUE TITLE
Crash Report -396160435

### ISSUE THREAD

**Issue by SteveSpam** [wowsims/wotlk#1529]
Link:
https://wowsims.github.io/wotlk/shadow_priest/#eJztUjFIHEEU3ff27pisUSYhxWh12UoCwtwuC7G6NZVFCkksLE2hlcWRLqkOSaM210asDPGMIIikOIs7QuIl6CUoVyieaGF1mBQ5bEQIZHa3CGqTwnR5xWf+e3/efP4fJysoqfkQwxhDgUWgBKyBH4BdoA086hbIUiNEAcvAXavvV2oamZGpZy8mngtHpvsqcKTc+Er17Zhupv6RnQqdlGxXafjFOartiK9V2DK8kLN1qta6bbTSHtXnmUQ7M1qX7Lyhah7SheX0yNP3VPurtpsyfpZzW55XTak512Kb4zLVdJ1Ot1w5oNo5sF27Fb87U41ibSmKjXIUO+XowvInqi+HUX4RV2ws0hUCGiPpsfSDEq3/uISXZjiSigU86XEobLP5jPkK6McsRnWQ8z3t57T29VUMeH6gA6N4Wnu5wAt8bU6+KQ5yA9eq/+AESrxrUC40qN42mP3eZP+PJvVpk23YP9E1D6sFyz3irbjB4mR4J2n1Xtg7/zrCVn4wYXbz9ydj7OW9VWafKvHPN/wqvAmX4tbmjfj8DZJZPT4Kh5L8PD+McfwGOr6BGA==

RNG Seed: 2446402973

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xe2120, 0x11ae5e0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/priest.(*Priest).applySurgeOfLight.func1(0x2a5a840, 0x7a80750)
	/home/runner/work/wotlk/wotlk/sim/priest/talents.go:313 +0x3
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x2a5a840, 0x7a80750)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:592 +0x126
github.com/wowsims/wotlk/sim/priest.(*Priest).applySurgeOfLight.func5(0x2a5a9a0, 0x7a80750, 0x2a80800, 0x2a809c8)
	/home/runner/work/wotlk/wotlk/sim/priest/talents.go:354 +0x1a
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work

**Comment by SteveSpam** [comment]
Wrong spec
