### ISSUE TITLE
Crash Report 109872274

### ISSUE THREAD

**Issue by martinstromberg** [wowsims/wotlk#1797]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUjFoU1EU/ff+7/fltZhnhvINKcQ/FUV5/z8CdcqzOGRwiAjSSVpEJxFxUqcgxdZMQqVgEMmoiKBRa1AoIjp0qEoHLYGWpInawcFQh2z1/v+bEDs51M0zvHfPuefed3lcnmI4Cjkowy/zAcATwDcAKwB1wA2AMc7AgRHQMA4JS8IoJO/bN8DOX5y8dv4Ks4SZXAEeF0830Pkx7Nrv3+JCFXlMvG6gawbhoJin3Pqwa26GrNJCp0isRiwuKpTrUB05F0LhZhOde4meIESD/HdS7l7yUwODLM9a6MbaVWx3a15Qk+n+Jh/r6MylQqEWTrP2naZph+HL5vZglvjQDM5KM5Cft3ryl0ZwlufRjTOQA3lrfM8EXIUZgEO30fiPP3A9xkDgZdobGBvitC3C0oM5O48JI2kzFKZzrgiHfSWlzEjleXSrIxQTkdLzlPSV8mRGeb5Uvqcy3jo4bHMJxdYSOg+/Yrq1jCP1ZZSdNdpH6ycMlGCONo6brHg2wban0DzJ97FbQ+mtLqAvF5hnu+bCCc0Ft9i3R+YOS3Vyh9B7oHAqrBHlKeyzBMrsq55yRtfAKKHhrmIsUi7p/VFwVB8o3Q2wmD0WKZ+yBy+E+Jz1H2P6tMP++W5N6d3oUlh8tyt9/gbRX51c1ccj3snmYAJ+AwCfops=

RNG Seed: 3313687806

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1d1d4a0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1d1d4a0, 0x16c0000, 0x1c4c200)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1c4c200, 0x1d1d4a0, 0x16c0000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com

**Comment by martinstromberg** [comment]
Seems to be a frequently occuring problem over the past three hours. Closing this issue as it is clearly a duplicate of other issues.
