### ISSUE TITLE
Crash Report 1383359632

### ISSUE THREAD

**Issue by nlautner10** [wowsims/wotlk#2030]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUk0oRFEUfufM7XnzjFxDuqYZ8VYidWdeU6zmsZqFxcjGkqQsLGTHSiJlQ5nIZCEUFgoLDTLJz8JiSlYoTIMSFmQz2XDuWNlZsPMtzv3O33fO7V7Tb2ADRGEejkpXANYB9wFOATKADwDNpgECasCBdvCiBN85GwY91ts50N1vuLnLtwFmMc/songOWPrxAaaSaLr5TBot1wtRD7+lXDZguV7JK+DjxyimKqklS+EctVC9yph8KYVizmuBZhbxG0rG/RajpEYSuT20dKpa3FYSK1soxgJEtnZQTPtNxidSamZczbwkLcZfl5V93FPl56T1HiB380IFtxfQojvJwhhrZx1YO4naP75hUDeAYx80l5seYszxRPUY9oBX8zEDRdc41IVsKWVY2naQTrueODkhGVRxFQzbwZBUPBzMgjDe0sg/0ihW77Hq7gxrMmcoc9fqe70AS4B2CVoCNesK3fkF9vudkq9VypyKZOXoU2syFWm08ziMVCdmFU4ioTWsahPGn7/giPMbKkMnR7+i8xM05m3LldP05eciUeiATzRneJw=

RNG Seed: 1401213298

Trying to spend negative mana!
Stack Trace:
goroutine 33 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbb480, 0x2c3d68})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Unit).SpendMana(0x1c21500, 0x1c78000, 0xc03f0bc6a7ef9db2, 0x14cdfc0)
	/home/runner/work/wotlk/wotlk/sim/core/mana.go:114 +0x3b
github.com/wowsims/wotlk/sim/mage.(*Mage).applyMasterOfElements.func2(0x158af20, 0x1c78000, 0x158cc00, 0x158cdc8)
	/home/runner/work/wotlk/wotlk/sim/mage/talents.go:364 +0xd
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:835
github.com/wowsims/wotlk/sim/core.(*Spell).dealDamageInternal(0x158cc00, 0x1c78000, 0x0, 0x158cdc8)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by nlautner10** [comment]
I presume to fix this line 364 needs to change to

`mage.SpendMana(sim, -1*spell.BaseCost*refundCoeff, manaMetrics)`

Since 364 only runs if refundCoeff is negative and I presume SpendMana requires a positive - being the error above.
