### ISSUE TITLE
Crash Report -168402845

### ISSUE THREAD

**Issue by mobmentality67** [wowsims/wotlk#2052]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztUj9IG2EU/36vl/RyreSrFLmKCdcbSisI390RSIeSSyfHQBcXoRVbHDoEp7ZTEAVx0cEKzVYoVIcuHSSDoNT+IUMkCI1QaAkqyYmDjg5C++4uS7eC7dbHx/F+797v9/143zNu6SRJUR6jmEKZKsASsArUgC2gCQTAGej+gA6LFPLwUcIYypiP2vrF4HJiBsnS00fPH0/rusTgDxhpudYl8yhjJ9e36UONjJRsHJB9KUyvykZAZjsTo7RscufLITvJqMOFfvn6gMyzjJ3iQnyMPvmuQ+Zc1tYYCYY7rLA81INpuRiQnVqrU3xYos0SJyyxE/FbP8N7zrm2wvds1HqOVg/Z0UaUtru9VJOtbvg97oSU70xpZCJrIUXwj8Y62X06D6KkjWnPwiEML5H4H7/Fiys6JJlUBq/Te2SNAV4ymAkL94Swin5iNDsuxMMiLw/JyQXcGckpz1Wu47me6ypHqZznMPaU56ic44y4KscdynH3YeqfN0m+OSTz0yZZ1a90+8suqe1dCqCd4nIV4htElYS9R6nIzNaEfy22dd2/UX0VRr1wN640CzefRNEquG/JevDP33LW/xsqlfrHi+io/HC5+KfN0aQqK/t+jxEUfgGTS5FK

RNG Seed: 3803891604

Character `Player (#1)` did not perform any actions. Either this is a bug or agent should use 'WaitUntil' or 'WaitForMana' to explicitly wait.
	If character has no action to perform use 'DoNothing'.
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbb1a0, 0x1c4a880})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x1c69600)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:319 +0x1e
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c69600)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x1c69600)
	/home/runner/work

**Comment by mobmentality67** [comment]
`__wotlk_feral_druid__currentSettings__` = 
```
{
  "settings": {
    "iterations": 3000,
    "phase": 2,
    "showDamageMetrics": true,
    "language": "en",
    "faction": "Horde",
    "filters": {
      "oneHandedWeapons": true,
      "twoHandedWeapons": true
    }
  },
  "raidBuffs": {
    "giftOfTheWild": "TristateEffectImproved",
    "powerWordFortitude": "TristateEffectImproved",
    "strengthOfEarthTotem": "TristateEffectImproved",
    "arcaneBrilliance": true,
    "divineSpirit": true,
    "abominationsMight": true,
    "leaderOfThePack": "TristateEffectImproved",
    "icyTalons": true,
    "totemOfWrath": true,
    "swiftRetribution": true,
    "elementalOath": true,
    "wrathOfAirTotem": true,
    "sanctifiedRetribution": true,
    "bloodlust": true,
    "devotionAura": "TristateEffectImproved"
  },
  "debuffs": {
    "judgementOfWisdom": true,
    "faerieFire": "TristateEffectImproved",
    "ebonPlaguebringer": true,
    "earthAndMoon": true,
    "heartOfTheCrusader": true,
    "totemOfWrath": true,
    "shadowMastery": true,
    "bloodFrenzy": true,
    "mangle": true,
    "sunderArmor": true
  },
  "partyBuffs": {},
  "player": {
    "name": "Player",
    "race": "RaceTauren",
    "class": "ClassDruid",
    "equipment": {
      "items": [
        {
          "id": 45993,
          "enchant": 3817,
          "gems": [
            41398,
            40002
          ]
        },
        {
          "id": 45517,
          "gems": [
            40002
          ]
        },
        {
          "id": 46157,
          "enchant": 3808,
          "gems": [
            40002
          ]
        },
        {
          "id": 46032,
          "enchant": 3605,
          "gems": [
            40002,
            40038
          ]
        },
        {
          "id": 45473,
          "enchant": 3832,
          "gems": [
            40002,
            40002,
            40002
          ]
        },
        {
          "id": 45869,
          "enchant": 3845,
          "gems": [
            40002,
            0
          ]
        },
        {
          "id": 46158,
          "enchant": 3604,
          "gems": [
            40002,
            0
          ]
        },
        {
          "id": 46095,
          "gems": [
            42153,
            42153,
            42153
          ]
        },
        {
          "id": 45536,
          "enchant": 3823,
          "gems": [
            40014,
            40002,
            49110
          ]
        },
        {
          "id": 45564,
          "enchant": 3606,
          "gems": [
            39996,
            40002
          ]
        },
        {
          "id": 45608,
          "gems": [
            39996
          ]
        },
        {
          "id": 46048,
          "gems": [
            39996
          ]
        },
        {
          "id": 46038
        },
        {
          "id": 45931
        },
        {
          "id": 45533,
          "enchant": 3789,
          "gems": [
            40002,
            40002
          ]
        },
        {},
        {
          "id": 39757
        }
      ]
    },
    "consumes": {
      "flask": "FlaskOfEndlessRage",
      "food": "FoodFishFeast",
      "defaultPotion": "PotionOfSpeed",
      "prepopPotion": "PotionOfSpeed",
      "thermalSapper": true,
      "fillerExplosive": "ExplosiveSaroniteBomb"
    },
    "bonusStats": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "buffs": {
      "blessingOfKings": true,
      "blessingOfWisdom": "TristateEffectImproved",
      "blessingOfMight": "TristateEffectImproved",
      "vampiricTouch": true,
      "judgementsOfTheWise": true
    },
    "talentsString": "-503202132322010053120230310511-205503012",
    "glyphs": {
      "major1": 40902,
      "major2": 45604,
      "major3": 40901,
      "minor1": 43674,
      "minor2": 43335,
      "minor3": 43331
    },
    "profession1": "Engineering",
    "profession2": "Jewelcrafting",
    "cooldowns": {},
    "healingModel": {},
    "database": {},
    "feralDruid": {
      "rotation": {
        "bearWeaveType": "Lacerate",
        "maintainFaerieFire": true,
        "minCombosForRip": 5,
        "useRake": true,
        "biteTime": 10,
        "minCombosForBite": 5,
        "berserkBiteThresh": 30,
        "maxRoarOffset": 14
      },
      "talents": {},
      "options": {
        "latencyMs": 100
      }
    }
  },
  "encounter": {
    "duration": 150,
    "durationVariation": 5,
    "executeProportion20": 0.2,
    "executeProportion25": 0.25,
    "executeProportion35": 0.35,
    "targets": [
      {
        "level": 83,
        "stats": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          640,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          10643,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          16950147,
          0,
          0,
          0,
          0,
          0
        ],
        "minBaseDamage": 38068,
        "swingSpeed": 0.75
      }
    ]
  },
  "epWeights": [
    2.379,
    2.15,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    2.51,
    2,
    1.67,
    1.66,
    2.28,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ]
}
```

**Comment by mobmentality67** [comment]
`__wotlk_feral_druid__savedGear__` = 
```
{
    "gear": {
        "items": [
            {
                "id": 45993,
                "enchant": 3817,
                "gems": [
                    41398,
                    40002
                ]
            },
            {
                "id": 45517,
                "gems": [
                    40002
                ]
            },
            {
                "id": 46157,
                "enchant": 3808,
                "gems": [
                    40002
                ]
            },
            {
                "id": 46032,
                "enchant": 3605,
                "gems": [
                    40002,
                    40038
                ]
            },
            {
                "id": 45473,
                "enchant": 3832,
                "gems": [
                    40002,
                    40002,
                    40002
                ]
            },
            {
                "id": 45869,
                "enchant": 3845,
                "gems": [
                    40002,
                    0
                ]
            },
            {
                "id": 46158,
                "enchant": 3604,
                "gems": [
                    40002,
                    0
                ]
            },
            {
                "id": 46095,
                "gems": [
                    42153,
                    42153,
                    42153
                ]
            },
            {
                "id": 45536,
                "enchant": 3823,
                "gems": [
                    40014,
                    40002,
                    49110
                ]
            },
            {
                "id": 45564,
                "enchant": 3606,
                "gems": [
                    39996,
                    40002
                ]
            },
            {
                "id": 45608,
                "gems": [
                    39996
                ]
            },
            {
                "id": 46048,
                "gems": [
                    39996
                ]
            },
            {
                "id": 46038
            },
            {
                "id": 45931
            },
            {
                "id": 45533,
                "enchant": 3789,
                "gems": [
                    40002,
                    40002
                ]
            },
            {},
            {
                "id": 39757
            }
        ]
    },
    "bonusStats": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ]
}
```
