### ISSUE TITLE
Crash Report 430743127

### ISSUE THREAD

**Issue by simonizeshow** [wowsims/wotlk#2126]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEuFgMmDKYKxgbGBknMDIuIGR6QIjoxOLAWMAoxCD1HrWJka2gJzEytQiDlYBNqnNjFz8Apv3MEm8lFVi23aY6dxZJi5OgR93mJSYD+9g4uIRWP+CSeKBLITHLnB5N5PEVBmg8G2glh9QYV6Bq9uYJFrllFiAPAYgdw1QzxQZJZavIC6nwJFdQNP2AxXyC2wBansPtAmoEGLgVKDOaTJcLAJdO5mA5Kw9IPLNXhB59yZIwZpXjBJnZbnYBNYlSXwUAQof3M2kxAH0I2MASwKL1gQmhlGAAqpYOBglmKIkuLgUmAyYLZg9GAP4gRHPIcAswaQgpMHYxahpYGBqbGAMIk2NDIGUkYGhgbGxsaGBqaEukAtGxrqmBkaPGHk4TjxlEjj+lEni4FOmF4wssxgzuAS4WDheTWYW4oBYaOfAxc/FzLEtG01gaw6awMM8JAGQIbtOwA1hYAApEfhjjVByi5FhFhODUosEJ0xEslpknfvDqiX2lhCRC/aKaWBwzd5oLZNCkAQHzdNDiwNVjHHYTx1ziACQsPK56+AI4f+w92BMYBwNL1xgNLxIA6PhRRoYDS/SwGh4kQZGw4s0MBpepIHR8CINjIYXaQB7eAEATiG8GA==

RNG Seed: 239680624

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xe2a40, 0x1168680})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Dot).basePeriodicOptions.func2(0x1c4d600)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:162 +0x4
github.com/wowsims/wotlk/sim/core.NewPeriodicAction.func2(0x1c4d600)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:86 +0x3
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c4d600)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:361 +0x44
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x1c4d600)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:297 +0x49

**Comment by simonizeshow** [comment]
I was working on AOE simulations and had mostly stock phase 1 armor, using deadly poison on one of the weapons. that worked fine, then i added 2pc terrorblade set (restores 1 energy every time deadly poison deals damage) and the simulator started crashing.
