### ISSUE TITLE
Crash Report -1010498957

### ISSUE THREAD

**Issue by brocwoodworthIBLX** [wowsims/wotlk#2139]
Link:
https://wowsims.github.io/wotlk/healing_priest/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE4MQgxSe1ibGNkCchIrU4s4OAVYpbYxcvELdOxhkngtq8S28zDT+x1MXJwCH+8wKTGfATJ5BJqAcg9llZhvAXnsAld3M0lMlgNqeXSdSeIHUMuSk0xAxMUlsHQfk8QcISVGBiD7/S4miXWSIDaPwEeg/okySswgVfwCDUBeO1Ab0GyI8W1AA6fJQCxjEdi+G0T27wOR3xeCyA+7QdauAGr7JQvk/t4LEty6i0mJg4PRgDGAL4JVawYTwyjACqrYOBgFmAoYJzEVcQVxMAn5cXFzsApC5FQcgBx2KEcBxGGCcjRAHDYohwPEYYZyJEAcRiiHwQGYnKQkGDkYhbg5/sMAoyJEUsShi1HdwNTA2MjA2NDQwFjXyNjEwNQQxDcwMjQ1MjU2MDAwAUmZGj5ilOBYeZpJYPVpYBI6zaTw+hKTxrtLTAbnLjG9YGT5wMg+i5HhFiPDLCYGpadMnGDjG9IcBGEWSc6aCQIn7S0hIhfsFdPA4Jq90VYmhWAJDponkRYHapjScPIIVcwhBUDCzOeugyOE/8PegzGB0UMCACQNf6I=

RNG Seed: 4125998828

Trying to cast {SpellID: 48089} but is still on cooldown for 998.24008ms, curTime = 48.889729098s
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbd340, 0x1c32880})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncCooldown.func1(0x1c84160, 0x1d84a80)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:249 +0x20
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x1c84160, 0x1d84a80)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:233 +0x26
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x1c84160, 0x1d84a80)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:192 +0x13
github.com/wowsims/wotlk/sim

**Comment by brocwoodworthIBLX** [comment]
tried to set up a holy priest rotation
