### ISSUE TITLE
Crash Report -936119605

### ISSUE THREAD

**Issue by sfjuocekr** [wowsims/wotlk#2324]
Tried to run my druid

```
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJzjkuRgMmCyYAxgSmBsYGRcwch4gZHxASPjC0ZGJxEORgUmB8YCkMQCsNwORkYhBqnZrE2MbAE5iZWpRRxsAoxSMxi5+AW2nWGSeCmrxLbtMNOeHUxcLALP9jJx8QhMXsQk8UBWiRkkxi5wYTmTxFQZIOMxUPiHLBeXwOqbTBKtckqMDED2wiVMElNkQGwegW97mZTYrv1ngujrWcYk8V4WyOi8xSQxTQZoetcykB0/loLIN3tB5LpFIJW/gTZ8luViAAp07gMaAfQdbwDLIqazTFwzmBhGAVYgZECqjioWDkYJpk2MqlzSHEwCjBKsCowajLYMDAqODqwecrEMDAmODYxywLTCIpAiwdjFGG6AB+iaGhgbGRgZGgMpIwNDI2NTY0MDA2MgMjQ2NTTUNTIwNsWh9REjwwtG1g+MnLMYGW4xMsxiYlB6ysQJdmJDmoMgxLEiDpKzZoLASXtLiMgFe8U0MLhmb7SVSSFYgkOLxqnjQ6MDNYxpOHmEKuaQAiBh5nPXwRHC/2HvwZjAGATOUcZgwOwg3/o6cIccM5Xd9sFeZJ37wyoRFofriwtsua4zOngAeevc/9ovAXEXMziArW2ltr2UA9JzFAAD5oVT

RNG Seed: 2906955866

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xee780, 0x12ee060})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).RemainingDuration(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:220
github.com/wowsims/wotlk/sim/druid/feral.(*FeralDruid).OnAutoAttack(0x20e5320, 0x1786e70, 0x207cc00)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/rotation.go:49 +0x12
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).TrySwingMH(0x2050d10, 0x1786e70, 0x2048000)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:501 +0x24
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).SwingMelee(0x2050d10, 0x1786e70,
```

**Comment by jarveson** [comment]
Can fix this, but your missing omen of clarity talent
