### ISSUE TITLE
Crash Report -563437150

### ISSUE THREAD

**Issue by simbaledo** [wowsims/wotlk#2734]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjYnBiEGKQ6mdtYmQLyEmsTC3i4BRgk9rHyMUvsO0Mk8RLWSW2bYeZvuxg4uIUmHqWSYl5P5DJIzB5EZPEA1kIj11g3RUmiakyQC1tW5kkfgC1AIXPnWXi4hWY0Msk0SqnxAIUYAByO4DyU2SUWL6AuJwCdy4zwYzoWcYk8V4WaHJ/H5PENBmIMKfAJJiVLAJdy0Dkm70g8u5NkJ69QD1nZYGM5i1gBqfAjdtA5UDDlRgWMQHtn8HEMAqwAiEDUnVUMUSpcEkJsEgwKTBpMFowOzB5sM5gDF3BaLOB0XsHo4YUmwAjUE6oi1HV2MDU2MjYAEiaGhoCKSMDQwNjIB/I1TUwMgWKANEjRh6OE0+ZBI4/ZZI4+JTpBSPLB0bOWYwMtxgZZjExKH1i4gRb25DmIAhxgIiD5KyZIHDS3hIicsFeMQ0MrtkbHWIqmFNbxRmQWJKcUZ5alK0QLMGhReP4/9DoQA1jGk4eocQcAwutAkdSNYFDsGHaIweozhf2HYyMQUhZ5oP9zcdeuo8W/bQn2egG3rCfWy/j0PfBPonl2pR5dz7b5y2dffvV1I/27F8VtQTcP9tr3p00VXvWW/v7rD7nank+k2wvrYGQwUaP+e9WCko48P2N4NiVxOJASAcAv6+dTQ==

RNG Seed: 3336735995

Unexpected cast failure
Stack Trace:
goroutine 134 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xcf540, 0x3333e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x20c0000, 0x1aa7290)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:498 +0x71
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x20c0000, 0x1aa7290)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x1aa7290)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:44 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).AddEnergy(0x20c0b28, 0x1aa7290, 0x4000000000000000, 0x2083e40)
	/home

**Comment by simbaledo** [comment]
I thought it error'ed me because of Glyph but seems im still missing something
