### ISSUE TITLE
Crash Report -1983089113

### ISSUE THREAD

**Issue by simbaledo** [wowsims/wotlk#2735]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjYnBiEGKQ6mdtYmQLyEmsTC3i4BRgk9rHyMUvsO0Mk8RLWSW2bYeZvuxg4uIUmHqWSYl5P5DJIzB5EZPEA1kIj11g3RUmiakyQC1tW5kkfgC1AIXPnWXi4hWY0Msk0SqnxAIUYAByO4DyU2SUWL6AuJwCdy4zwYzoWcYk8V4WaHJ/H5PENBmIMKfAJJiVLAJdy0Dkm70g8u5NkJ69QD1nZYGM5i1gBqfAjdtA5UDDlRgWMQHtn8HEMAqwAiEDUnVUMUSpcEkJsEgwKTBpMFowOzB5sM5gDF3BaLOB0XsHo4YUmwAjUE6oi1HVwMDU2MjYEEiaGhgCOUZA0tjY2MDY1FDXwMgUKAJEjxh5OA4+ZRI4/pRJ4s55pheMLB8YOWcxMtxiZJjFxKD0iYkTbG1DmoMgxAEiDpKzZoLASXtLiMgFe8U0MLhmb3SIqWBObRVnQGJJckZ5alG2QrAEhxaN4/9DowM1jGk4eYQScwwstAocSdUEDsGGaY8coDpf2HcwMgYhZZkP9jcfe+k+WvTTnmSjG3jDfm69jEPfB/sklmtT5t35bJ+3dPbtV1M/2rN/VdQScP9sr3l30lTtWW/t77P6nKvl+UyyvbQGQgYbPea/Wyko4cD3N4JjVxKLAyEdALminUs=

RNG Seed: 3478658841

Unexpected cast failure
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xcf540, 0x3333e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x222e000, 0x2205760)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:498 +0x71
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x222e000, 0x2205760)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:479 +0x50
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x222e000, 0x2205760)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x2205760)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
