### ISSUE TITLE
Crash Report 520241527

### ISSUE THREAD

**Issue by TommyMccormick** [wowsims/wotlk#2743]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztVE1oE0EUznuJ6WZM7TQU3caarnsKSmGSJYcKMqsXb9rWiwepevAPPFRP2lMsSDWIRdHSRmxApVaEeihIKhj8Q9pioEJaxZNJaY0/aC+FnNTZnd1iQcXSevNb2Jl573vfezNvdkmjghQZHoMOSAIMAUwClAEqgJOISYSdGymooAEDU1DOOxR8B1gB2OYJecJDVV3gbzlx6MzhU0qAkvBDIDV0qIzqYET3336GmQwSH+3+iCRIr5dQvRjRvWNZJFX0Sg7Vaw2CPSjYxXrdL6gWm9AB4UlFdPCI+bciqlcbrHmAVoqoe6dFcA1NC6kvm3S/kJJqd0RMb4NIdSmHgnp/DmWeIM28wUVekM5O4E9Rj9+j2h0hHhGXyqFerfhYdYt3n/e0tdebmEfSh57/+CVCbLkRnX4FVNSgCzcQooC8WlEIBwLS32ymYCtjCYPFY3HDaGpiRoIZ4knEmBFnCSYQs95GzLCMJVCVgQLS3gKqI9Oo9RUw2lNA1j+FZfDNQ1UaFoCoxKeM5iFEZZI60x60oybRhGfunjekLvGYLc54wGZY98dlzHN7SO52GO0mCZN1yoX12ncXEFJcLqEi+sYoOhYRZVsu512LULCqo5kn6Fa3Ryon22V1L5LeP+QWasoDwXDUFLP2iI1pngV4C2trpb3CNX8aPfoMOud83Kx1d1yf7rcwzpulZZJvdjXiI6jtVdds+cdfwPxZczVkkuPPV0VnOZBn9uiruUOuK/wgtNn/jMZzn1qzkSlu2JiRrXNbuAJkI5bwMD+5nby+1THLP7dalle82Fk3vKs4wdtswtii/3c6sut3+dL1B+72XuqVnPUc73m6EN3fU1px/SGWf2lBMf824gcAu+jB

RNG Seed: 641109247

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf6f20, 0x13dcf50})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).registerSummonGargoyleCD.func1(0x2116630, 0x1829400, 0x2180000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/summon_gargoyle.go:38 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x2180000, 0x2116630, 0x1829400)
	/home/runner/work

**Comment by TommyMccormick** [comment]
Tried running the dk tank sim with a build that took Summon Gargoyle in the deep unholy tree.
