### ISSUE TITLE
Crash Report 313572777

### ISSUE THREAD

**Issue by Somatics23** [wowsims/wotlk#2840]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztU01oE1EQfjPZbjaP1j5DDpvQxrggFFHYH3LoQd7qQfGWevLgoQoKikj1Zi9GYfEHRTEUNCepePBgQIQSD6KmvQSJRAtWPAgaq5EqjaLV4MXZ3UakClKo4MGB7zF/38zs7Hu818QcDsMpgDpAE2ALahBnqU9dJ0DNHdx9dO8RDUU0NQ28V9y9j/p0v6FOTOL4U+Qx0X6NRqRURd4tvlHsUX/HGmugPtZnROplJF77Huo3kob6sIZ+mIvTFdS9tAGM94ibRCz0GQqlMmIWKmiopIfMeQqeS//kuPYG9SvJwLFQ9ke40MCwjSK8qn+eDc7rr/wxPMqu0VDF2x2rsGgpouGhwcaxhvwSsv/yW4mby2WMdumYB7gIh/germkgUFcyICC1gaMWISBBIQChi6ASeggxAiesIkRNZTCo5h5zNwfKgaa7PWww6O6E/YE2ctJNaXQ5IQMDyhlYZ2ZNx8laG03bMbO26VjkMC3HcWzbshzyWnbWegnd2uNZFBNTqD+YxSYoLYgWgT0DVkRmNDAW1M5vdVeH/RJusnjZl6oMZ2J1uXZfIE+kfQszOV1d/5dvUOu4uxJl8tWpFamzHAl3dmd+8T+yr3IYdgRvLtzqB3l4E5+5OtKWHUZp24vRROnLDzsROD7KJYXZGm9uqJx+L8P8mSXxlgx5C/IdZXlzb+Xk54Fd5ytt6VtD5ee/1PtXJG7SOmgnCTf8MnD/xPgOy9+ylg==

RNG Seed: 2832617555

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf8140, 0x13f7ff0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/shaman.(*Shaman).FrostbrandDebuffAura.func1(0x1a0c900, 0x20feb00)
	/home/runner/work/wotlk/wotlk/sim/shaman/weapon_imbues.go:313 +0x7
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x1a0c900, 0x20feb00)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:598 +0xfc
github.com/wowsims/wotlk/sim/shaman.(*Shaman).RegisterFrostbrandImbue.func2(0x1a0d200, 0x20feb00, 0x21feb40,

**Comment by Somatics23** [comment]
happened when I selected Frostbrand Weapon in my offhand and tried to sim (simming for PvP)
