### ISSUE TITLE
Crash Report -1892183645

### ISSUE THREAD

**Issue by maguma** [wowsims/wotlk#2874]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1HfWJka2gJzEytQiDhYBNqkHjFz8AlsmMEu8lFVi23aYaf8OJi5OgZPdzErMICaPwDag3ANZGO9uN7PEVBkl5q9AHr/AJqDcD6C+efOZgIiLV+AdULpVTokFKM0A5G4Gyk+RUWLZD+JyC1ydyqzEysAAMklAoLOHWeK9rBL73Z1Mm3YCpfkF/jxmkpgmo8R27izUFWtArrizE8R81Al1EIvA7k5mILkcSPIIbAQachbuuHvdCB6nwNoeoBag0Uo8wPBhDWCJYElgqWBcxHSWiWsGE8MowAqEDEjVUcXCwSjBFKXKJcDBJMAkwaQATIwWLA4sHqxSggJAGQURg/8wwNjFqGlgYGpsYGxoYGJsamQI5BgZGBoYGwMFTA11gVwwMtY1NTB6xMjDceIpk8Dxp0wSB58yvWBk+cDIPovRkIuNi4Xj2WpmML3rBDMXKxczx8M8LgEuPo5OMQWEZSAFAhPPMt1iZJjFxKD0mYkT7OCGNAdBiNNFHCRnzQSBk/aWEJEL9oppYHDN3ugwU8HzBqYqdsec9MSc/DyFYAkWLRonnA+NDtQwpuHkEUrM2XD+U7MjqZrAAdhw5pMDVOcHew9QoRMEzm22XNcXF9h+sj/8VSOm/9Bfe2INrRZZ5/6waov9m8Adcq2vL+LQ98EeYv43e/nW10CVX+1BukTWfbcHke4PX9kDLQXa/J5oe+kFhAzADm5ld4CkQ2YHQjoAoo3R5A==

RNG Seed: 1042089925

Unexpected cast failure
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xd7180, 0x355088})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1b7b640, 0x2022210, 0x200e000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_generic.go:300 +0x7c
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x200e000, 0x2022210)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:35 +0xe
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x2022210)
	/home/runner/work/wotlk/wotlk/sim

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
