### ISSUE TITLE
Crash Report -488178032

### ISSUE THREAD

**Issue by Maarslet** [wowsims/wotlk#3106]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnNmG2eHNW/iw7jswjovWhTM7CK4Qt5bEBj0sBTRz0NpoFT0I0aCvrRF0Q8E/Vig4EsQCSUWUiwhtaAvUpIgBQXWqmi79dAuKC79n5lJAl9CWnvqMN+de8493zln7j13tAoVTaiBeohhA7RgHCCFb/E+YBJgDCANsLlMBR1CWAUCdkML9AIkAEqxBvwPlTOgxI40tje1qsiK/K9BK2FnM6hngobyaAg/J1DzstEUGvICTX3sSxr1VNCQh0grYg9mUb8RIMo3MueJQk62XzHro5V7QcMzl0CJ1DytdwYMz7ytlrDcNBrepwl0HzLEKWXcbyiUb8ox3H6P+s2AoRB/zqkhN0k1uNMrxJZtNw+bnbTHdMYubZwoo0HXyccuTLvakOP36Tkair1RMc8tnEctidJ/+SspNZfL6PCpwFDHXtCoSa9Bq9asaWSSdQyBCQz86zVUZQISPAQgrCIohGKCl6ARVhOKTIw6YcUpscmZtNwRW91MURGjRj/kWs8Lv0q9DSG5Ci9BpVkdMSOmVR3eYL+rTTNi0Ri2IhHSLStshW2DNQU+9fEwssFh1J/NYBo8WVC7QXoDUjdKxmXZ60RPHhBr3Jxlory7y5YR7tYljfGKZkde8fAEhnbo6roVbrvsaVGIMPGR4YLEWQlx93bbxK8zl/K8Hhpgu3OluXMAOZ5p6+xpOpbni5yB610n+g//1vOsv6785QJfElra057qGAzk+NWxg41b2t4tWc/yvh8f2p4MfOV11l29cnSGn4we3b9x53c+y9ZWRo5/XPQXBf7kfyalZu3Fc7tqo8XiRVzM9+wD8SfG3mX/BH4CEXDEkA==

RNG Seed: 2004622323

Trying to cast {SpellID: 58704} but GCD on cooldown for 1s, curTime = 2.733817202s
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd9140, 0x20cbc90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x207e630, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x207e630, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core...

**Comment by lologarithm** [comment]
This was fixed last week
