### ISSUE TITLE
Searing totem crashing enha sim, Crash Report 1392806495 

### ISSUE THREAD

**Issue by Saltyc0der** [wowsims/wotlk#3114]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE1IVFEUfufcaXzz0LwNLp7DDIxvo0XBe74ER8h7CwKDFkMR/SxKA6Win8FI0E1TEOFP0I8FDrhpk2lhIkWZyYCzGUJyk4vAnARDa6OENIvIzsxzTNyEpK06vO9yv+/cc+559573tBIVTaiEGghjLUQwCpDCj/gMMA4wDjALsK9IBR2CWAYSjkEEegBeAnixEnxv3NfBHT5f11zfqCLP830CrZD33mb6XMBwvxjF569Q8/BkOzNYZprPe8iXChhsYinDhr6hft/v+Lw81c70dMDwEHMerYBPkfYkYLiIKUT7KLzTv0wLebSDrV5eyB+TP+oz3CvCQC/TH/hXBA+fbl2uxcOHcmW5+Egvo/F1K6OiBjqYPhbIFbyauXisjRnuzIGFXQ9xEbU4Kv/tr8xrrjeiJV8Fjjr2gEbNehcatQZNI4npGAQTOPh2aqgyAhJcBCBsIbgJBQQPQSNsJeSZGMqmlVfl3uwk8kgecHYKyTA1/FlHvSl9KvU4BKEM26DUrLBN27QqynfZ5m6zwjRti8Zyy7ZJtyxiGcGahnx1NIF8OIH62xmcBdc8qDFQPoASQ8W4xTzZ7PHTcpuzZ5EsjnVlLCmcupRxUdKQtQlRPonBw7q6Y5Pbbv6a3Ig00WRiQ/Jshjlne3By+c6VtKiBWjiU/aRF9gIWxFxTZ3f9xbTIxQze67rcf+43T/P+6uL338Wa1Mrx5lTLsH9B3Bk/U7e/aWqNf148XfrSNDL4Q1RbfXrp2Iy4Erpwas+Rn+Iz315qX/qaWy83+JX/mXnNqtYbR6tCBfJdVC52nwT5p4gT6/4J/AJGcL6M

RNG Seed: 209131622

Trying to cast {SpellID: 58704} but GCD on cooldown for 1s, curTime = 6.797737118s
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd9220, 0x1a78890})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x21854a0, 0x21e2a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x21854a0, 0x21e2a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 ...

**Comment by Saltyc0der** [comment]
Looks like searing totem is causing the crash?
