### ISSUE TITLE
Crash Report -1817277406

### ISSUE THREAD

**Issue by goldiejay** [wowsims/wotlk#3451]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjYnBiKmAUYpBqZ2tiZAvISaxMLeLgFOCUWsvIxS9w/AWTxEtZJbajh5j27GDiYhG4P4UZKLzuO5PEA6Dw+p1MZ3cycbELdDxlkpgqw8UjcOgFkxIbUOm5syDhs5+ZlBgZuHgFTn5mkpgio8QClGEAis9+DBbnEZj3Daj85Q6w4ewCXa+YJKbJAG3Z8w9k1+snIPLNXjD7GRPQ3ulAe88C7T2zkwmIuBi4OAWmfWdSYn60k0mJYRHTVyauA0wMo4AiIGRAqo4qhiIXLjsBxgmMjAqMBowWjI4QcTsHTzDd4OgQCBGJdIiEMCwdKhhnMDIuZIRwTRykmCSYuhjDjQ2MjIDYwMjY2NjA0MDUEMg2BCJjI2NDI1NDXWMjUwMcQNfIAKgHO3jEKMEx/zKTwNzLTBIzLjMptFxm0nh5gceg/TLTC0amD4wssxgZDjEx3GJkmMXEoPSBiRPi7jQHQYj7RByMbjMpBEuwatE4fX1odKCGMQ0nj1DFHFoASzC5970DNJX8sE9gDALn3MNfNWL6D7E6yLe+Dtwh99eeuvZ+sPd4WCWyzv2l/TeQNV8ZHMDWtP62B/E0Yhgd0sCAxQGXCUDFQB3zqOwu6gEhA02wVyQdlhTYcl1fzONASEcUNK9/INpPADdhng4=

RNG Seed: 3401652898

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x111d40, 0x15eda60})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Deactivate(0x0, 0x1b9dad0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:628 +0x2
github.com/wowsims/wotlk/sim/warrior.(*Warrior).registerHeroicStrikeSpell.func1(0x1b9dad0, 0x1b42800, 0x1bd9b80)
	/home/runner/work/wotlk/wotlk/sim/warrior/heroic_strike_cleave.go:46 +0x3a
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1bd9b80, 0x1b9dad0, 0x1b42800)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:502 +0x13
github.com/wowsims...

**Comment by goldiejay** [comment]
https://wowsims.github.io/wotlk/warrior/#eJzjYnBiKmAUYpBqZ2tiZAvISaxMLeLgFOCUWsvIxS9w/AWTxEtZJbajh5j27GDiYhG4P4UZKLzuO5PEA6Dw+p1MZ3cycbELdDxlkpgqw8UjcOgFkxIbUOm5syDhs5+ZlBgZuHgFTn5mkpgio8QClGEAis9+DBbnEZj3Daj85Q6w4ewCXa+YJKbJAG3Z8w9k1+snIPLNXjD7GRPQ3ulAe88C7T2zkwmIuBi4OAWmfWdSYn60k0mJYRHTVyauA0wMo4AiIGRAqo4qhiIXLjsBxgmMjAqMBowWjI4QcTsHTzDd4OgQCBGJdIiEMCwdKhhnMDIuZIRwTRykmCSYuhjDjQ2MjIDYwMjY2NjA0MDUEMg2BCJjI2NDI1NDXWMjUwMcQNfIAKgHO3jEKMEx/zKTwNzLTBIzLjMptFxm0nh5gceg/TLTC0amD4wssxgZDjEx3GJkmMXEoPSBiRPi7jQHQYj7RByMbjMpBEuwatE4fX1odKCGMQ0nj1DFHFoASzC5970DNJX8sE9gDALn3MNfNWL6D7E6yLe+Dtwh99eeuvZ+sPd4WCWyzv2l/TeQNV8ZHMDWtP62B/E0Yhgd0sCAxQGXCUDFQB3zqOwu6gEhA02wVyQdlhTYcl1fzONASEcUNK9/INpPADdhng4=

**Comment by goldiejay** [comment]
Related to #3450 --  Closed other ticket.
