### ISSUE TITLE
Crash Report -811356806

### ISSUE THREAD

**Issue by where-fore** [wowsims/wotlk#3503]
When starting a fresh APL, selecting the Mutilate Spell bricks the entire website. I cannot use the sim or press Restore Defaults without a crash, meaning the site is completely unusable unless I clear all my cookies and cache - which works great if I have backups of my saved settings and APLs.

Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1HfWJka2gJzEytQiDkYBNqm1jFz8AtvOMEm8lFVi23aY6dcOJi4WgWd7mbjYBW5eZpJ4IAtkXFvLJDFVBqiwbSuTxA+gwsM7mM6dZeLiFZjQyyTRKqfEAhRgAHI7gPJTZJRYfoG4PALf9jKB1QIR0JSeZUwS72WBwv19TBLTZJSYD4Pt6toLJpeByDdg9t2bIOUPljNJnAXZvngZmMEicOcKkxIX0LOsASwRLAksi5i+MnEdYGIYBRQBIQNSdVSxcDBKMEWpAaOSSYJJAZj6LFgcWKTEgDxGBRGD/zDA6Hr2zBnbLkZNAwNTYwNjQwMTY1MjQyDHyMDQwNgYKGBqqAvkgpGxrqmB0SNGHo4TT5kEjj9lkjj4lOkFI8sHRvZZjAyHmKwWAJOvuJQoF48SFxfHJkZWLmaObyZSEEpIRkoKVcIIyJZi42LhmPWH6RYjwywmBqVuZk6w6xvSHAQh/hBxkJw1EwRO2ltCRC7YK6aBwTV7o9tMCsESrFo0TmAanQ7UMKbh5BEC5gRTxR5yACRs9753cITwf9gnMAaBs64t1/XFBbaf7A9/1YjpP/TXnlgTq0XWuT+s2mL/JnCHXOvrizj0fbCHmP/NXr71NVDlV3uQLpF13+1BpPvDV/ZAS4E2vyfa3sEGhAzAHmtld4CkY2YHQjqioJn9A9F+BgChibgr

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x113a20, 0x161cd60})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*APLAction).GetAllAPLValues(0x20e5380)
	/home/runner/work/wotlk/wotlk/sim/core/apl_action.go:43 +0x48
github.com/wowsims/wotlk/sim/core.(*APLAction).Finalize(0x20e5380, 0x1967dd0)
	/home/runner/work/wotlk/wotlk/sim/core/apl_action.go:16 +0x7
github.com/wowsims/wotlk/sim/core.(*Unit).newAPLRotation(0x21ba000, 0x1ac8ba0)
	/home/runner/work/wotlk/wotlk/sim/core/apl.go:93 +0x93
github.com/wowsims/wotlk/sim...

**Comment by where-fore** [comment]
As a follow up to a similar issue
cleared cache -> new apl -> Not, Aura is Active (no aura selected yet), Strict Sequence (any ability)
Also hard crashes the site.

Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1F3WJka2gJzEytQiDkYBNqm1jFz8AtvOMEm8lFVi23aY6dcOJi4WgWd7mbjYBW5eZpJ4IAtkXFvLJDFVBqiwbSuTxA+gwsM7mM6dZeLiFZjQyyTRKqfEAhRgAHI7gPJTZJRYfoG4PALf9jKB1QIR0JSeZUwS72WBwv19TBLTZJSYD4Pt6toLJpeByDdg9t2bIOUPljNJnAXZvngZmMEicOcKkxIX0LOsASwRLAksi5i+MnEdYGIYBRQBIQNSdVSxcDBKMEVpcPEJMEkwKQBTnwWLA4sHq5QYkM+oIGLwHwYYXc+eOWPbxahpYGBqbGBsaGBibGpkCOQYGRgaGBsDBUwNdYFcMDLWNTUwesTIw3HiKZPA8adMEgefMr1gZPnAyD6LkeEQk9wCYAKWlBLn4lRi52LdxMjExWDExcUhxcbFwvHvN9MtRoZZTAxK3cycYDc2pDkIQlwr4iA5ayYInLS3hIhcsFdMA4Nr9ka3mRSCJVi1aJyMNDodqGFMw8kjBMwJpoo95ABI2O597+AI4f+wT2AMAmdQW67riwtsP9kf/qoR03/orz2xJlaLrHN/WLXF/k3gDrnW1xdx6PtgDzH/m71862ugyq/2IF0i677bg0j3h6/sgZYCbX5PtL2DDQgZgD3Wyu4AScfMDoR0REGz9Aei/QwAqJ2zYQ==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x113a20, 0x161cd60})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*APLAction).GetAllAPLValues(0x1bdee80)
	/home/runner/work/wotlk/wotlk/sim/core/apl_action.go:43 +0x48
github.com/wowsims/wotlk/sim/core.(*APLAction).Finalize(0x1bdee80, 0x1bac900)
	/home/runner/work/wotlk/wotlk/sim/core/apl_action.go:16 +0x7
github.com/wowsims/wotlk/sim/core.(*Unit).newAPLRotation(0x2116000, 0x183d0e0)
	/home/runner/work/wotlk/wotlk/sim/core/apl.go:93 +0x93
github.com/wowsims/wotlk/sim...
