### ISSUE TITLE
Crash Report -1697306757

### ISSUE THREAD

**Issue by ghostrider7795** [wowsims/wotlk#3585]
Link:
https://wowsims.github.io/wotlk/mage/#eJztVG1oTmEYPvd9jtc598b77PHR8Wxv5kjm1bbzvq83n3mP/cFCQpJSJJPQlv3w8UNLDeOHHyR7CfkhJG37xUqtxY+lzVeESbMRRczWNCSe87FZWdPCL+4659zPdV33dd/n66EcHWfBImjDR9oFgBrABoA7AG2ArwGKSAcT8sCBNcAV0W3sg9DybRt2b9qhG0wVj4HC7GQPmm8jVuhmI968hmSw5ja01FaZZrITkmuPWGqtt3raheahiM+FWbXket26a+jSo9j+DjRPcUuTK4UYe/4CzWM51kjJt7pImH19h5bhy2s9i7S0OCAtWj2JBF52onk8p9/TYJUfglkM9uxVkGqsp8s9t3S4Q53uRvNzpI9p9pgvH9EK62DDcm2Nth52wUGAc9iD1IDK//it4PZwK/Zk6sCwDCrcrxOKskmuq8HnFjsiQ0eG5kZLybuMh2B6PGHb8kgkYrZtJ/JtO5m0JRTzMJkkE7G4CySSsXYYq3c3I/vWjObFl5h76x7mvbgnP3utEzLSoDRit3oWgMaRLkKk6VdqVMugkTQiP14wq5zGUEhohGZWAMYKZpb3a++24ACY5whBLDpaH8GxWHEFhMnyPlO+TCyhIu5QVjSsaxxXKEIWkppITiFTjCejDqSSXa9S+9LLMnXFvp0njvt+7Gg98ojI9mh1cHqumE2FPD8w08+2ImXUgU4hN80FGhPNkqXGJXTZw7dRBDO7OS8U+TSZT6JMi0iPu2hDzU/DxOL+zUmKF4tFNJ/PG9hNRE23Qb0HtF3QhJHG4KEN3VwTOEfhE0XEk2lew6D2TQt6sk8tyGOikKZEJweC7Do0deA/eojA/W5QIks5if73VhX84zOcJ6CkUbHOqIYHVJQ4WT411pmQrnajKTXbR+6kJpV48TAVf49lb4/gntDC0h3bS7fmrjRD0b+8b+RVOX/CpqLpxi98Vg7FO1dPliz4E3MMFv5zXt3hVMOW0s7KplUPUkGv3tSKIXfmdV07l0472p66fyxj7+Nnz1M+2pkqPz966uYHjf3rwa//Tgx/Z1477Irvpgr7xQ==

RNG Seed: 793065459

Trying to cast {SpellID: 42833} but GCD on cooldown for 42.675864ms, curTime = -1.7s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xe9ae0, 0x1a26b50})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x2028630, 0x2088000)
	/home/runner/work...

**Comment by lologarithm** [comment]
looks like your pre-pull actions are too close and so you are trying to force a cast while the spell is on CD.
