### ISSUE TITLE
Crash Report 617287455

### ISSUE THREAD

**Issue by mialdi98** [wowsims/wotlk#3863]
It's because of "Settings" -> "Fire Elemental" -> "Use Tier 10 (4pc)"

Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE1sTFEUfufe1+mdY6q314Q3V8v0bYxB8t68DCWRN2yI1WAjYlELFkJSZsVqSETaSpQgMUskfiLCLJpWI5m0TfwFbVBBKEJC/JWonw3ue2+KsPBXC4nzknfP+c53vnvueT9Yz0gCGmAhZEkjNJE8QBvAXfKangBSAugDmB9lYEBc0bKwDJrgMEAHgNBkiW2BUHbtyo2rNrBKXikfAFbzo23UeFxnhtp7yGAnwTAv7qEm9dwIP6xyd+tMWvKj263U2FWOqvkxlXvn1XWSgY8Eq/igSpcipq7SGnLepcLdtWalCgc9RPD8dmrsrDXDARKoHFEqH2K+Sn+HB5w8So29tT5Q8ts51kqDLcP8fnPZ1XlXM1X3Q+oe4SeV7kXVV7vf5deRzgst1GSMWJDVl+n7yTDBEtH+2x+ZsH61YlOYASeG97LuAgM1GWXEoHFIkBQyypVnqTe1BaZYacdyLDudmmFZaXU5jrdatqMcx7YdO+XYVtq+DxF2qpfwnl5iXHhIHoE+BGMKoHWTK0oXxyGTIdRZoUU3K7EC6QwnhzUYkjoSo6YM2TmhSzJHE7NkGqeJqRhLTmC6YGu8yufnqQyjItqWtS6HERORFUGVsUvjZZkg6uRErDGrsaoIKAivUPDVbeCn1SpMGcfxSfUtinA3eGDnQSqVBELa5wzkqWiQM3G6SPq8kb3789TLI7FyyJNjWUiQRVqANORkmSFQBme8/JV/494X3+sgLidhNCkYFRUtlDBd+idPWbmR6Xxmn7lGRUxOwCpzDIaLfrebN/tteOtZchZuglYgmtlKw/4Tza/O1ATPNpqJFfZ5ds6dHSB9bv1q3wbc1C0SX2pUJP/yR5dozoyGTP5c7w90lo7KPr9jwWxPv8jMC+J3biMs8X9nwfRfuuvn4vUDTe/dkYrjC+5tih5/+zmO+sAr9xthbfLWJ4s7Jj1zA/71b/JDblD3xn2qWFufPHZ7hhMrdnS/d71occed7/T+NROWGpuaXTQTTAAyP6pYXv4BDv302T8Bl3vsFQ==

RNG Seed: 2912552675

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0x11b4e0, 0x1756870})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*SnapshotManager).CanSnapShot(0x0, 0x31fc2c0, 0x5c631f80)
	/home/runner/work/wotlk/wotlk/sim/core...

**Comment by mialdi98** [comment]
It's because of "Settings" -> "Fire Elemental" -> "Use Tier 10 (4pc)"
