### ISSUE TITLE
Crash Report -994632261

### ISSUE THREAD

**Issue by Shaklor** [wowsims/wotlk#3876]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE1oE0EU3jezSXbHhGzW0G7GpsZFMEYKm4TgD8hGL3pM7aWIBz1YRBSquWhPqVC0qWARUcxJ1EOVUmqxoVULoQ3YKmoFbVFB2oLQUrVVrG1PdXY3CVIP9aceBN8us/u9971v3ryZXbJRQBraBnshgY5APUoBtAKMoS+4E1AOYBhgEmA3FUCBAApCAmqhHhirDaAHoBOBzNG7whmwJ44dOn34pCBKDjoOxC3dbsXKlF+1ZwdQthcRUZpowSrOsVen1MZiY/4iyrdgZb6A3FI7iy0Yeb1oZAkRl7TEwk2VKs/CHJGk+wxeqlAdDGYNj1vqZsKiBS2JW0xixpKwHFfOY+VyhWrPWQ5Rai/WwspqLrzyUnczZmMfG51SB0t5worKmiXe+Q7xUiaNVRfrGyT4WtspOAdwHc0hkkPcf/sjk7VfzWhwCiAhBV0D41BeBD/hqE9ACg7gIIq4WRAbB5dtVdpWC2nYpMWiWlQLxyJVUS3GLi0aNsZwNMr84bB5a7HwBDiFe3kkPcgj5fE7NAn8LDgywPWjPiZO1hKB2gkvZNK86iA2gquiSeIhdsoTpHgKrnBS5inawckqDZCykFcAWewHI633JqaMQSBmqoyksEyopfjiLJT4vCwcNXzPU9iIEaQlaQHLfrqOeFQ3cXUBkZFks1JLEkW5Z4waoJXEG5IFLNvSGAk8NcuLFMTYEuStNEa2yJuJL1RemvTjI0xFwqhhTTueJE6VEKELWKLwtIwWCKVpXo1j2UfLiUtdQ8Quc42NjWbRxrNEe/gSD6JBeA1cBnFqCxbNPUzVxT3WbnrjvsxVw4b07ZZnWN9QZ9qIHnmDAjWKLfSXP7Ngc3w1ZFJD+RV0alZlnt8xq7d9M/FdFl7QD8I+8wdmdf+TfmInGb1Rv6gXMzr2jDd4O+ZL2Gs6PuvLhLn1TdPVPZUfdIs/uiw+q1t5X/X3jNU0PaUPzAUPXOhf1A1U3fP2B71/zWSNtY31zhu3OgDxlTL2F355sz+99m/2Ie2U

RNG Seed: 1494912235

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0x11b4e0, 0x17568b0})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*SnapshotManager).CanSnapShot(0x0, 0x32468f0, 0x5c631f80)
	/home/runner/work/wotlk/wotlk/sim/core/spell_snapshot.go:47 +0x2
github.com/wowsims...

**Comment by Shaklor** [comment]
After resetting sim settings its working fine
