### ISSUE TITLE
Crash Report 442519187

### ISSUE THREAD

**Issue by juankamilo** [wowsims/wotlk#4008]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnPu7O7sRXMaJKbNNR3CRChmXbb0oWbyqaKHpV6sHrI/KahYfMki0IpyVUoQ+3HrQRLUJCqQJKNgya1YQdwHEYxKsSJ7ciUjE8LOzmgP9hCS9tSZ+12+c8495945c+byXAl1KILtEMQyCGE1wCi2OB8CRgESAOMAJZkSqJCD+WBCKYSgA+AxgCJ4ml0XwBk8cfDM0QrJJbs8g8Az5B8NTP3s1ZzdvTjSg9wtD06gxlI0TW68wtRRr8Y64yntbT1Tv3ltX4Z8lXzTFEfa0CzydLnvGlMvZWtidw8KpDaQvylLEylWoOXhJGpuWksjasWPfkd1guJJa4unDDdqmHo9yzJErYOM1TKN2fRe/RwV5a5aRvPdD8hd8pfLTO33EgmHLSLKkTqmpacqFBRLHZUQBriDX5FHUfgvfyWKvtiIs2kSyKhiB3Bq0kb6FrxCBs9GjhIjIEEkAMFBcBLSCW4CJ6wguLigY7GVzawyt1kk1G7usDfYawapv4/b1hqzIoMa4WJNqhEUUR5oYpVA+3oUCXMgHws5nYbRbwE61MF6PeDX/bovULjBrwfo0f2+1Ozz+8nu81lDD/jGIE16EkP5aQzV3hiOg5gEVwS2cpmL0qckKJJ9lExzgcUM/mY5YHKnbXmOwmsQIigMz7Vlnqm9R7dFq8vNlfM5V0eaUxI37BIICSO33JIho7ALc/aojoKby9vYyfPmUqSpjseWJM9ixK7Zs4m5thGmjTLYbV0Fb6yqThq3WhxNa0PTxnxEfP+6RMmumV+6sqkg79zYlLEgsdDZ+C5Z3D5pFIUL6k7OvlzgTxpHhsd566kZIzAslmUf+2iMQPRB36spo6r/0ebMVZPGi/tthxJrHOZyvPW/EEXfGRwY8txWzC2tRacPBwXzTxH7Fn15/ASk+9I0

RNG Seed: 1896279466

Spell {OtherID: 3, Tag: 2} missing CritMultiplier
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0xe1760, 0x2a59390})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*SpellResult).applyAttackTableCrit(0x318f0c0, 0x318ef00, 0x3019b00, 0x3fe2e07083982102, 0x325fa18)
	/home/runner/work/wotlk/wotlk/sim/core/spell_outcome.go:463 +0x1f
github.com/wowsims/wotlk/sim...

**Comment by jimmyt857** [comment]
Duplicate of #4052
