### ISSUE TITLE
Crash Report 1423435325

### ISSUE THREAD

**Issue by ParzivalBV** [wowsims/wotlk#4039]
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 25 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x11b480, 0x174fb30})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Spell).PhysicalHitChance(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell_result.go:94
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).setup.func1()
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:49 +0x11
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).setup.func6(0x322f9e0, 0x3000000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:115 +0x1f
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).run(0x327ad80, 0x322f9e0, 0x3000000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:398 +0xa
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnGCDReady(0x3000000, 0x322f9e0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:57 +0xf
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x322f9e0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:449 +0x21
github.com/wowsims/wotlk/sim/core.(*Simulation).Step(0x322f9e0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:508 +0x25
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:465...

**Comment by ParzivalBV** [comment]
https://wowsims.github.io/wotlk/raid/#eJztmG9sE3UYx+/59drdfht4zBmOmpByL7Dian5310PWhOw2hOALkupIGBoSbuVwDaWd7U0yyOJCYpRpIiExGXvhPzSiRo1/XhiDQf4YhmOK28CAkRjCImpQEzUhvsHnd9dBcRBqrfFNn+5Zn7vf/ev26ff5Q1/U6dh8ekTcCbQjk8ttiqy1s1ukoEzDKhVu9VIlSWRzkoGuwCvkD0I/JULN/pU1sX96xnZhJ5lLRQkiEA41iTIogSFYwphparpmGobBmMEMnWkM3YgZzPReaLoRw8POgyJdmibyC1NE2TNFIsNTJPrcFGF7T5GLIP4KdSNQP2+zZ6fbDhOiwCgZhY8AzgKJhEaIcKb4T19s0Q+RotCK3NZu20WCQmURRCXCgkmxS9wo1hiqilXC0MMLqSQThSwTLTHcRIkMuAWRZrY7sHL8xInlQxBFVjyM4lo8xnRTZ6bGOTJMjpZuaLjONN3UzkOjdBiBOjZNlDNfXoVIuMrOWRCux2Y4uBMaVmZ77GzK2epkXYnIdWWxE0J2IFnjpjpWCTd7YBBoD6WSzwswkCHcQokUQCfoIjqgB9FD6HPQ69Ep+lz0uiiwQKt3NesJq90Lel+3HvBv0GoloQvS/t6nrHAzooECF4Eo0aWZew7BXYgmqpxm6qhvcY9KzqaucfkzNA23+A4PzY+PEvnAUaKMTZeD5leoaIEVKGch/FzlIjmnhmSVrBIk34elNIqUBJESWC4Ig5YVXL1gN9w2DIENSFn7ICx8DbioYRILU8pTZp28iXN0d8yMo8YhN7qhc61DrjTdS6AcHy2mc7lD0HSeNX8fb5RfvUCUzw6SyMgpEj02QdiRiVKqhBsydRaZElf15fsxR9aXWWURFsIqq4ZVdawSrPJt1JQhQqLEFykhaj3oB+ut9X7QavVALwoiPA3wMvj74lYYpSMCCkGZQraw6kJ8jGIhhsUZw0xqzJDm5VONw7V/ksgjk0QZniSRA1dI9IeTjezJyVvC1STQHxfQc5hQaTKfc52Um85lkTOxVs3/D1YJZ59DiAphwqv4aIwDYWoGIsK4Jmk8oSEnhq7FUI4MXtJzeeLAfHuayM8eIsp70yRycYJEv0c1mr5Ojd4FBdQ3gb4OO9TCY32Os91Zncv0r8vbbo+acPN9Tou6zU67nRk7tUVNIJstaqqv4Oa2PpRzbQ6SmsAze51MpqAmHimGamLpQMvVeFlJ3FoS6yWxURLfVxJrJbE5sGFg4OaNxj4uofzhy0Y7JGFtkiQ1sKtiFeVlLPqEsIgVHErhYtNrHEzelSLaXP046abOyeYiqXE59MDec4jIzyPYb98U7JsVb5e4DN6fLqTSvZl01pECcrBMGeSszO0K1mipilXUWJD5SMvtCkjgDTWkRf5Ks+WV+3yigYxgLYbU8JRqePqI7WdMxwyKpZvh07N/jMgvjRHlANLzE9LzM9LzxXX0fMBl8R2gb6Esuv29jppQV/SnMo5anvrF8TC74BaSTn5NOtvn4vlaqQoum70eLxXA2culWqnd4Ooz0jiL933Iu7R27brIqnTekUQ5UOYABliDN4CpqWN1rBLeO+Yi7lQiSkr1cB+Ce3SvOuT9K757szree/DqkfEqwK8YOfp+xfjbOJGvjBPlDST9ApL+HZJ++ZxPeoNH+mYEvZtu3KF2Z5CpdWm3J9fnrkkXCumM02Hn8/ajTnt37nFnjZ21EbiUk3XVBLtXb1Fz2Uy/0Z5P2Vmng5/b6WKJUOhwMrltfztYMz02dxUhiluzKB3F3F3XYWf4tKfstrrBk2SxK4ildY3SqlgllOp30nkSIJ/YBjFYDUnoGoVwyOuh61GY+QSQCzMfPHN15hMYzikyq8Vifn9T7J6nDhL564NEOYPd85/nSBQ7Z3ZsohTXYlqfQUmfhRI2O43XGKnWlkwSwhJBJTJ438RgeBOdT++AGxlfEEWR4A8a/gryNzS+gI8o8ucURSEoisGA99DFhWs2g7H6TKDeCwY3W/P8Xc3WgpG93I63+QMy4WTboplJvP4NiXQqwSX/8fcgusuqxmUGjx+9xXU6q3KfSsz/237yS3H4KFxu2wh/AW1jVLY=
