### ISSUE TITLE
Crash Report -381502431

### ISSUE THREAD

**Issue by sarahbau** [wowsims/wotlk#4040]
Custom Rotation is empty
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0xe1760, 0x3aa860})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/common.(*CustomRotation).Cast(0x0, 0x52f06c0)
	/home/runner/work/wotlk/wotlk/sim/common/custom_rotation.go:124 +0x1a
github.com/wowsims/wotlk/sim/warrior/protection.(*ProtectionWarrior).doRotation(0x2be9c40, 0x52f06c0)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/rotation.go:20 +0x5
github.com/wowsims/wotlk/sim/warrior/protection.NewProtectionWarrior.func1(0x52f06c0)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/protection_warrior.go:62 +0x17
github.com/wowsims/wotlk/sim/core.(*rageBar).AddRage(0x39d2b18, 0x52f06c0, 0x400c579288484868, 0x32e6280)
	/home/runner/work/wotlk/wotlk/sim/core/rage.go:138 +0x36
github.com/wowsims/wotlk/sim/core.(*Unit).EnableRageBar.func3(0x3324b60, 0x52f06c0, 0x402e500, 0x402e6c0)
	/home/runner/work/wotlk/wotlk/sim/core/rage.go:95 +0xa
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitTaken(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:779
github.com/wowsims/wotlk/sim/core.(*Spell).dealDamageInternal(0x402e500, 0x52f06c0, 0x0, 0x402e6c0)
	/home/runner/work/wotlk/wotlk/sim/core/spell_result.go:258 +0xaa
github.com/wowsims/wotlk/sim...

Complete link:
https://wowsims.github.io/wotlk/raid/#eJztmXtwVNUdx/ece7OPazDHlNbrDqHp7YxmmKRz9y7bQmY6rI/O2Icz0Thjpp1Ou6a3Zuu6m2424GOYAjUNiRAHFAWmKiqiwvAIDwkkSCCkBiPCkGjEjCKJCSgOCUIQwUq/55zdZVFQm6b/5bj3es/jnnuGfD/n9zha3U3aKkPb75xHPL+JzbSrQtXltpsyl/dDouWwtY8o+kd5hvOVNtq6jWoe1j1EDYU/ZrPFCxX9g7xU7fwJqi+ZJGu5bAS1s3mGZ/Ve/h5vm8BeX6LoNZMN9ZVt1KEx1oypH59kuNB5mLfksPnD1PDI4W9foGj48lFFH8LXD8spctiTtYr+xCTDmZzTwz76hyI/6WF9dclHlW2qU3B/+UO+roeHqL4Pq3z6GV5bdOxiTWXL6xXD6aYmKVGfoyNUa6WO8fI/lVzzv33jQcdiMkv7AyPeQo26FVwUl4qL4MrC5cQ1AZcHl4bralyuAmIq08UEwb8FbxQPlS8GfynnnB4sIWUkLFtrg3MI8U50U13JJwXU0tyEUZ3kE5PUkxvMgN/0m76AVeQ3p5oB0/T7cLd8fj/afT7UeIOvj2S7t++hrGUP1TsH6DGiDhPXcuLYTTFVB+0g7xLHcuo4lBTQ9UHtOReIuhlERRPhaMitsCxvLyeqb7GifwJNj+ym7UK3zUdAVKNgaP8CRe+DOntE7YV6Ra9P1nLYAfSBKCdG9gic+k9R/Z+5htrO4ZnAhs5Qfd11htojWdrSoBgedDWKHxpOon/FZPF+u2gYqFH0FdcZzh45oYsdrlP0OZPx4dUN/EEuSmUb+/l91xB/ZwSLaMAk7XISB5Z/gi+/eZAabjf+RUuuLssaR2lMyqhQot/THN4cnbhJruNHsnViUMjc9FuQMhc75GxB8qhYfp8V8BVZ/oDPhNBNfx/R3S91Uraik+otAzT/+EFacOIgNd88CMlfNUwUIflNRCfGOqKtIQ8ZiQcqbaPYuPmB8ohtFBrl1VWJ2H13xBKhRDgWNYofMqoq7Uikyij+XfLRKJ6KYaGqRFWJHb8tHK1O4H3ftNmF6f5pX++fmtH9s693WxndvsvMPvv3s2dfFtJFgNR5px2Ph2x3FlO973BCd5ym+scgbWUbXSYIbTsDiXc0cSb/fZ7q/Xmp2nMglNu8rcLmLW0QhHpQkz9QeRCQ1sPmbZWQzvmCcpunDvJqLluPNx6dZHhg7ZJvwObhCyfw9V2phgMAl9s8rIV/1cX2LlEM4gCT/cLMtR/lfG7Gs4t1gM838rCydtjauslyZSpbe5rjqZoTSpQyZRzPMSmjwfN14gSeMET1pKCIG5uAzx+wTFOQyE0OePRbvqIAKqZl+tAlkHzvbcoW7KJ6I5A8BiSPAsmBg5lWaD1HcjXRXgSSVX+ttu0H7VtjkQfuiocSFUZxIl5tFxqzQuFEaSRUfq9RjE3gu7H600wuM56nZzxn0ufPBDWTyoznQArHJgIiab7zUiZrwGRWmR1tWwkkPd5XOZIvzVUEkk3vJJHsXKCkIDzdl4lkdw8MtNtQlgl2mrdQfa7XcKJPdq/ZTPWBianBn/bRdJ+HnT2SxvwU70gCl80JTNdU1vQBvx8R7L1xhj/vn8fZe3iA6o/lYZ7ekeQ8KlsD8HKYqmdJ9O4n8wkZ529Mymj4Wy35y6f1ZIoF/LgxtPzw/CzQ6IcVtEQrwAtY3B5yJi0fJ/DZLsqO4A/8ZBfNr+miBbVd1Gy5AALpMFEFgVs4gRuIthYEfheyrCvScXmCrkRiJnFTr0CozwRyhUZF1R2he+w7K+J2VUUs8ie+DXwDhw0ICV2/5RtIuBwkat59BCxsh6J5NMgDNA9buRAYtgh6Ntbicb1wXJ9PmsX1wiwOwARuvs7wYJj8wQ52o60121BRc2gaqxsUZpFwm7gF5m4RbCJeRu96gfEzQPxLuKqoyYbOJTIOTE6osneXK1jDtobkclS2SvD5yDAffQJW8SVvejQ3nds4mIj8JkxD7FemjoM5dmU0YJ4jUzXdTRkYCpJbSQmXZAchBzhexKtfI8cNz8gnUxwmuTH5HhzboiK4teZUv8DWgifLmfaLOM7ycdOK0M4Uvq5fRHG6+6luypZ3w6XqpvlLu2nB0reoueyt7xDR5Tq0zyZr7VnwGEtjfw6HoyJL8jyHYjc8MuemNvqy8LZaOkQ6AiZEeVkEVtthWKDtbPYYcHEe2kafRrPGHoaqn8jlPRrb0EoNdU6TcBI/gG1zrdpL8eMBVicXNVaA9w+jx4lRn7Tx75w+ze8HhNBXD/Lng1/wz/0r5R/u2ijiN06siM3GI7OxKaNR+N1TIHAi8xNzSoK3y4dgMEgqiPdqN/HytITCUxQ8LfFjbo64drk7yA2T3xIhG4I1OI0yTcHF3LKHsgMwS617aP7592nBOTiG+7iYXSmzdKX0RB90rJWGouWJ6qpI9f0i+nmXu1qbFir6cbha21J7fCvXX7PY2BvRdyQvVVvXT/XPkrVc9nQy+kFt5V7aLKKfNmzTh92G2iyjn9bzMkXRLFMUXOd8uPxhih7s03WYAu8np8hh9UNUZCmaZcZP5VkKLGp1QzrZ99mz/N5/lC+pHfHVxxPlklxsJ8zKMTc6576aQoCOIzAmZTQIbKRueF8qtk34X9cHTGzavoDPFPEP9O7j4VDA4uEP98qwZ1sy+lm8i7IliH7WfjX6+VaRD0Hknl9H7HDi7ljsPreTEW8313jNQpmDa99Ne0U4sf1MOqv994UyB9crJLQFGq/PgzZPnZIJ7Xahw0Yh7yOZGTjGdjTIhDaqvVLhe3kSrjGdhMtl6zCkFrP0iiEyMbd5kfRl2i9V+LlBmsrAyc19eb9IDyyWGbhGMYPwZZbVK8ZVQt1qWda4HzNWZTQSt67VrsE+TnRaQE3hyJR1EC/+TPXkBqjd4ik4H7Z2noezhE+COrReVGSJTR1DuOK7d1LWs5Pqh3bS/HPY1tug+NeSKbhvVvxJKD77V7FQNFFhzwonyiuwsbvlxr5rflr0MvH81pl04nnPfCn6xksSz1KzGcpv/KryG+XGvmpEbuyNUvabL5V9Dls5ks49y4a+GkX/NC/dkM3er7uYcs5mTYgBLiag3xwW937OYxdMxLk8VN9bINwe+DYalz7c+KzxzPMYldEo/y8T4cUq/FilAH8OL6wty9LhyVwPZfPMs58nmDkCAeHHWNKZCQi/3QwI1R8aoOypWkXv7aT58xBjfwnVz+3KTDw7Lqv5w6555KqbquPRcPSeB+14DPs8laeXcz+nqdPLLiH5NVzyG4QEX2sQp5dO1LpknvWoOMB0bh2kO5p4w4WzQvh8BPeELh5gbkgmcz+XydwNMpl7EqaCJ3NRlT9MMQ9DhuQUsmFHMpmbbJB5pGz2Kpov5Mmlqez4YCqCzWG1J6l+CjN0yRdEFAGXaOkkMdhw89PLaePnl2NVRiP94p/DrZkOt+aH3h/wGLaABJVblaWEtBIFQew7hCRPYoZnTN/3Bi+fzJAhbPCZYAE/hOROPY9PTeH78NhVJKf8SQPhF8xIj3/FfspegMe/Es5QD5yh1wHJ28lUsISkhSeithJt88XTmVKQEbHvDMXvsRNGoVGVQJ032/FKO5ooFdVCIxEPVd5lh2baqYTxzHClHS9NhOKJ20LRUIkdL8doo9j8iS/dF6v8Spe/0AhFIrFZv7i/MhKrCs+0SytiiVtis6LxUPTe1MT3VUcS4VtiiUsWIPoue0yDyDsbyk/+N1Y1RosdUxyGCmutiDv1Wtq12vfJ5QrvUFWV4oeCWxb/H4pxlHpqjt/eNDnv3qDVS/NL9awp/2cMC+qCYzHNnL17vmWe0jH5zmiKPNnfMZQ82XecnfFH8h8bfD2C

**Comment by sarahbau** [comment]
I noticed that it is able to simulate after deleting the warrior tank, Xena. This character does work in other logs.
