### ISSUE TITLE
Crash Report 1045079049

### ISSUE THREAD

**Issue by lkmuniz** [wowsims/wotlk#4069]
When i select Paladin -> Retribution it happens

Link:
https://wowsims.github.io/wotlk/retribution_paladin/#eJztVE1oE1EQ3pldku2jtc9QZA1NCQtKLBQ2WQL2UN5WDxYVie0lSC5SihZEQ04aL620YASJaFFbEPw5qIfqQZAIRUIjGGkLUgRjvbSFaKD+tCWxRaX17W5aVEQt1oPgd5h98833zbyF2SX1MvpgO7RACMNwHLoAzgFMYlG8BZACSAM85TlAAWDHZhkoKODljhCEIQpXAWyZS3D3OE6BI3Tk4ImOGJdJ7kEglfTeJKqO+xnMpJBU0NxrVMW8dexLiKposhLNzSGppgufUFn0qA7OmTSh106LSm+dCgKpoh94sa9WlbjXTJMFVJ1DKRwy02pa5NX33Jq3GOKk3QlRuVjLW2cTIo9zRXPMqykzPubDKulL3nvMo4qmXODsYBFVWUatKiSFpetYQpJG4T/+CC5trY64UwYF+QbulojgFs7AFi2o6QFN9zc06IGgFtC1oD/Ao5+zuj/o5yc96J8GRb45gvTuCCoP8uidGUffm3HU3o1jAaRZcA5AK3GTDXJik3d5BeCSy1MNQokkd5/FVUYgKleP7vtaTe2KbFiPdLsxjEIWszABwgAKL8rbstVQL4gVtiRmbLTJRiOwhNHSFYy79na2H/bu6Tx6yOtr6Ygd62zf5m1T5Pq/vGy+hLEebbqePPpFn7af1Yu5S5eb1+MeP0KjGeRpaO6H85GlnR/fZlh51iLjC9VqfdFN5PmNaJNk1NzZNRWvmWcrZt1CZjU/aQmesYF+E7eZ7ZtgNt/DUnW9M/tTD9m3V5hlkeRwyRdZZtYjOc8sG1lgrZahwMZGTXz+zvfvwKXZb+IxftdxYM3/gC9ig9gO

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x1170a0, 0x1746d30})
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.FillTalentsProto({0x3a2618, 0x2bc6c60}, {0x2860150, 0x25}, {0x1a, 0x1a, 0x1a})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:709 +0x1d
github.com/wowsims/wotlk/sim/paladin.NewPaladin(0x2bc8000, {0x2860150, 0x25})
	/home/runner/work/wotlk/wotlk/sim/paladin/paladin.go:177 +0xc
github.com/wowsims...

**Comment by jimmyt857** [comment]
Something is wrong with your talents, your settings are using 05032031--325023051223010323151301351 which isn't a valid talent string for paladins. Try going to top right --> Show Sim Settings --> Restore Defaults.
