### ISSUE TITLE
Crash Report 1134258502

### ISSUE THREAD

**Issue by Sam-Hunter** [wowsims/wotlk#4212]
Link:
https://wowsims.github.io/wotlk/rogue/#eJztVl1oXEUU3jNzs5k9pMndyU9vx13cXmvcXI3ee3dvTKqy25ZCaCwEWrSKoKU0JibVkhWJeQpFoUlEg/WvxYL0QewPfdi6gQQEaQttoa19kNL6YgnW/kCpWCtFJTr3Z5PdJEaK9c1h2Z0533zfd86ZudzFJIMkdMImeAm6YTsMwBDAToAxgC8ATgKcA7gAcBVgdXUW2uXOAReWGCetIKaqd0C4s2/zm1v7GVXD4hpgjfrlGNWuxfXw+DFSmCAYUb+9SXSal9MqdVxil+I6LXirz0eo9mHMX3H10ijV7sT1iFydnCDfy9gSde8w1Q7FdUWyQ6iqt+SWD2J6pQQLbqRGPfIu9Rj+RwZ+fo9qN6X7TODK21T7KKaH8xNBOiM7qW8ZUaeG5fT8nwQVdf8P7veRYSrzeusdqp2JF3P+atRf+ZSzo9QDdGTEhE5lkzIA+8htgl+T0P/jXw1u3i3jOgkNKgw0eJ4LVQWNJOrMMdoKa8+cPv3UCCRN00nZpmWmrXSzaTu26VimY5opR8ZsO2VJ3LRsx5qCKnb0MlFPXCbaxW/IVVB+ArYHQkfJLaZRjGJYKEi0qF6JFUibrRxXBFkZ4i0ijQ/zJqw3apnC2SRIlP2aFvIHwULVqGZhTtaFRBgl384JH+drxRp8hBvYYNSV8bxtVm4+kddy5s7Z9O+EVxZlBsQbuI33YqOxokymIU9qGXD2isv47A/i52MHsnQHhPxICpkdbMEH9QdwuXG/1InmSbVkl6ZdVpnr/Jx4FtfzDq+A8NwC0n4BUOLkYJWOJW5Ro4ZVeBZeRy0zJwKIvy76sZt3oc3NheXtnBenf2NbWmB6jq2LV8xW1jrragsTG/mKBRTciDLLSfucTyVnm+jFzfzFRZtQrnWfsUxGlkwCcqJWBIfjbW/JlcuM986ze0ZsxHW8/S7sYoaYb1fWcFe3VkSR5UsPuNDHnxBt+JhoLgKFvuByuH1Ymid17vU6EEBlzfzxIOWOSGETf8hv/r6iwFKj3s17huUl4jw+S3tSrERTPFriqRuJwFPLk/oyz9Iy1F2ThMeEKJ7VYHBWjulpnz1OF0Gv76I8JSxM8kbkhhrcD4YSs9pacguw/PPh60UHruZZj6TMIWlGg6w1cgAChyBdZxE5FDNP+HcQuhi8TRqz+mEa8aZDXdmoH6zLLtuz2x2nMm1+5FxmeZc3zmfsabL99l4yyJ/u2dKd6Oh59eVEsn1r/2s9W5oSGzRm/MfvqeRw9l7IDJ06/g86GxbDf7nw8Ser7kUeCw2v52wKVu2G91+YXvPbjWOZwOtORv59+gt2yTyA

RNG Seed: 2336334668

interface conversion: *rogue.Rogue is not hunter.HunterAgent: missing method GetHunter
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic(...

**Comment by kayla-glick** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/4225
