### ISSUE TITLE
Crash Report 594506661

### ISSUE THREAD

**Issue by scrublama** [wowsims/wotlk#4258]
Link:
https://wowsims.github.io/wotlk/retribution_paladin/#eJztUj1oE2EYvue9S3L3Ue2XU+HrkUq9QUqgcD8W1CXRSToFunTUwU4OYhd1ChKH2kGHVrCDJg5SVwXpYKG1Dg2Y2KmgoqY2QtShHRS6FHwvV1MERdS6+dxxvM/zvH8cr8ia1I+jOIUCjeAiisANoEGf9RlgFpgHlpkDLeBkjwkJhT6uKGAE51EG4jRbc0qpK0gWzp25dPaCKaThrEJ0y/IaqQ+9bvLRItVrJCxZWyNXfzxL7M2tkmqwxywSuuQUJ09lYtuWFWabva4V25G2R75tkrp60DWYaULKEqdMZtxU7Gvc83qLXOt2leKXu9QbpNa/69It73CXm5nOYEvONLeXsuSbb/sZ8n4z+n56HpU840m1nV01Nt7XyU3KhDI83KUvJOZJ+4+/gu39bsVH0i6nTCjisx0yHDJxDQVvkB/f+wEG2PgJ2ArCwBv0Ay8MQz/0Aj8MAw5C/x26zIkFkq9XSJUWqAVjA6lpaE94qtJFWiQdQ5BKuymREPqAP2bzJsc1WzimkxSGeW+LOnG5onfixckdfZz1A84+YT1ARDcqeluucGnGcYTM7jUTNg1pkSroyFjbfbhFS7SEl9BebN/e4bw7oVvtsDiaT8fi/nzP9K0I1dyxWFnOHRptYyUXvKK+YZXI/uPr7R/P70abYvXpL/oM78qcP0H8b+fW8ydivpk7ja8ZL6cm

RNG Seed: 0

Empty DefaultCast with a cost for spell {SpellID: 31884}
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xcc720, 0x3030ca0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterSpell(0x2980000, {{0x7c8c, 0x0, 0x0, 0x0}, 0x0, 0x0, 0x12000, 0x0, 0x0, ...})
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:266 +0xf2
github.com/wowsims/wotlk/sim/paladin.(*Paladin).RegisterAvengingWrathCD(0x2980000)
	/home/runner/work/wotlk/wotlk/sim/paladin/avenging_wrath.go:32 +0x3e
github.com/wowsims/wotlk/sim/paladin/retribution.(*RetributionPaladin).Initialize(0x3030150)
	/home/runner...

**Comment by napnapnapnap** [comment]
Any idea what is causing this ? another link

https://wowsims.github.io/wotlk/retribution_paladin/#eJztUj1oFEEY3ffNere7GG48LCZHTs4t5AgEZvdYiNWtVmK1kCZlLExlIVbR6lAskksR4h+mCGIlB3IiGhRRErXIIYnhiogGIQSCp00sFNPp506MaCNq7HwMy/fe+743w/J5vQ6V0Y8jSGgQI6gBE8AqfRA3gHvALLDEHOgAh7sdSCiUeCLBIE7iGmDa8lahnjmLTHLi2Onjp6RdWIGXkwsTQr0t+pmZJ9S8T54r7zaELxa53C2fs7da9EUzZa/rQn0qGi8nn7G3yXPsLX8mr0veaQh1fp9vs2B5Uj7g7os9fpa7UyUnL4wL351JaTONWOSIDRNhhNsccblnW3DlrW9vceXa6FZpy8lxwd9HDeHl5YtzQi0UfXe6ReZ4FntXxoTvOKS7EnsI1+kjebNk/cdfIa9/d+IdWWeyDhTxwh61C6TEGJJIVyIdRKEOtQ4qOqoEWkfMw6CPrZC1IGTrR/T9LHzHGpRzc53k5BypS3NUetOmcqdNer1NHdjvkZ2C9ZhIYZ7m8QrWy61FOBD7deGmZW043mPEvXH31NWvaFUPGmWpun84xXI1XKHSgNrV+49XqTwa70RMrfX0FzkDO3LPn8D824cb8SHDN6tD+AKkeZQ8

**Comment by napnapnapnap** [comment]
> somehow managed to not have a race selected, which confuses the backend code, just select one and it should work

from discord
