### ISSUE TITLE
Crash Report -485094695

### ISSUE THREAD

**Issue by repsejnworb** [wowsims/wotlk#679]
Link:
http://192.168.1.239:8080/wotlk/deathknight/#eJzjUuBgMmDKYCxgbGBkXMHIuIGR8QAj4wVGxheMjD8YmS4wMTkJKDAZMDowRgDVdIDVCDFItbE2MbIF5CRWphZxMApwSa1n5BIQWHWYSeL8PSYltm2Hma79Z+JiEZi6hImLQ+DmUiaJ4/dArP5lTBI7bjMB1R7cyiRx8jZQ7byTTHt2MHFxC3QDdR8BijAycPEJHAJKX1/LrMQClGPg4hE4tQioFMgGqgZqPrmISeLZaoRmAYFJt5gkXgDVg9SARFgEupaByPmLQOSbvSDy9XkmLgYgZBHo3sekxAX0N68FYwBLBIvWCSaGUUAVUMXCwSjB9ItRnIvNgdGDMQCUVrgFIXIf7BUYuxjVjIwNTA0MDEx1jY2ApLGpgbGpkZGBsYEhUMLAwNjY0MDQ2NTwEaMEx+wrTALTrzBJvH3KpDDjCpPGjKtMBjOvMr1gZPnAyD6LkeEWI4PSZGZOsOENaQ5Qa0QcJGfNBIGT9pYQkQv2imlgcM3e6DGTQrAE06CN8RIHapjScPIIAXO8qWIPCEDCuOOwgyNUwCGBEQCGqXZx

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/wotlk/sim/wasm/main.go:45 +0x10
panic({0xc9460, 0xf73c40})
	/usr/local/go/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).applyKillingMachine(0x9a96000)
	/wotlk/sim/deathknight/talents_frost.go:149 +0xd
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyFrostTalents(0x9a96000)
	/wotlk/sim/deathknight/talents_frost.go:45 +0x1c
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyTalents(0x9a96000)
	/wotlk/sim/deathknight/deathknight.go:202 +0x8
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x9a96000, {0x2eb530, 0x93ffe00}, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, ...}, ...}, ...)
	/wotlk/sim/core/character.go:157 +0x37
github.com/wowsims/wotlk/sim

**Comment by repsejnworb** [comment]
Happens if you remove both weapons.
